# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{brute_squad}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Powell"]
  s.date = %q{2010-04-08}
  s.description = %q{Sick of authentication frameworks with all the sauces? Me too.}
  s.email = %q{fauxparse@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/brute_squad/USAGE",
     "generators/brute_squad/brute_squad_generator.rb",
     "generators/brute_squad/templates/brute_squad.rb",
     "lib/brute_squad.rb",
     "lib/brute_squad/model.rb",
     "lib/tasks/brute_squad_tasks.rake",
     "rails/init.rb",
     "spec/brute_squad/model_spec.rb",
     "spec/brute_squad_spec.rb",
     "spec/debug.log",
     "spec/spec_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/fauxparse/brute_squad}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{No-bullshit authentication for Rails}
  s.test_files = [
    "spec/brute_squad/model_spec.rb",
     "spec/brute_squad_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

